#!/usr/bin/env bash

sources_file="$HOME/github/TheHadiAhmadi/dotfiles/dmenu-scripts/dmenu-websearch-sources"

# dmenu theming
. $HOME/github/TheHadiAhmadi/dotfiles/dmenu-scripts/dmenu-theming
prompt="-p Search:"

# Eval awk output as real variables...

# Output label string to rofi...
search="$(dmenu $prompt $lines $colors $font <<< $dmenu_labels)"

if [[ ! -z "$search" ]]; then

    # Retrieve data...
    sel="$( awk '{ print tolower($1) }' <<< $search )"
    txt="$( cut -d" " -f2- <<< $search )"

    eval "sen_dsc=\"\${$sel[dsc]}\""
    eval "sen_url=\"\${$sel[url]}\""

    query=$(echo "$search" | sed 's/ /+/g')

    xdg-open "https://google.com/search?q=$query" &>/dev/null &

fi

exit 0
